version: '3.8'

services:
  whmcs:
    build:
      context: .
      dockerfile: DockerfileHub
    command: [ "/bin/bash", "/home/script/hubScript.sh" ]
    container_name: whmcs-website
    env_file:
      - ./env/.env.hub.local
    restart: unless-stopped
    volumes:
      - '/home/amir/htdocs:/var/www/html'
   #   - '/home/amir/htdocs/metrics/logs:/var/www/html/metrics/logs:rw'
      - 'management_logs_volume_hub:/var/www/html/metrics/logs'
    #  - 'management_logs_volume_hub:/hub/logs'
      - './supervisor-hub.conf:/var/www/html/supervisor.conf'
      - ./bash/hubScript.sh:/home/script/hubScript.sh
      - ./supervisor-hub.conf:/var/www/supervisor-hub.conf
    networks:
      - my-services
    depends_on:
      - mysql
    ports:
      - 8003:80

  mysql:
    container_name: whmcs-mysql
    image: docker.iranserver.com/mysql:8.0
    command:
      - "mysqld"
      - "--sql_mode="
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: whmcs
      MYSQL_USER: whmcs
      MYSQL_PASSWORD: 123456
    volumes:
      - 'htdocs_whmcs-mysql:/var/lib/mysql'
      - './docker/sql:/docker-entrypoint-initdb.d'
    networks:
      - my-services
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    restart: unless-stopped
    ports:
      - 3309:3306

volumes:
  htdocs_whmcs-mysql:
    external: true
  management_logs_volume_hub:
    external: true
networks:
  my-services:
    external: true