version: '3.8'

services:
  rabbitmq:
    image: docker.iranserver.com/rabbitmq:3.8.19-management
    container_name: rabbitmq
    hostname: rabbitmq

    networks:
      - my-services
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  nodejs:
    build: .
    container_name: nodejs
    hostname: nodejs
    ports:
      - "8080:8080"
    volumes:
      - ./../view:/usr/src/app
    command: ["npm", "start"]

networks:
  my-services:
    external: true