version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"  # Portainer Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for managing containers
      - portainer_data:/data  # Persistent data storage
    networks:
      - my-services
  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaeger
    restart: unless-stopped
    command:
      --metrics-http-route=/metrics
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
      - 14269:14269
    networks:
      - my-services

volumes:
  portainer_data:
    driver: local
networks:
  my-services:
    external: true