version: '3.8'

services:

  openstack-mic:
    env_file:
      - ./env/.env.openstack.local
    container_name: openstack-mic
    image: openstack-microsys-iranserver-com-openstack-mic:latest
    environment:
      FRAMEWORK: Laravel
      VIRTUAL_HOST: openstack.localhost
      VIRTUAL_PORT: 80
    depends_on:
      - openstack-mysql
    volumes:
      - /home/amir/openstack-microsys-iranserver-com:/var/www/html
      - management_logs_volume:/var/www/html/storage/logs
    networks:
      - my-services
    ports:
      - 8002:80

  openstack-mysql:
    env_file:
      - .env.openstack
    container_name: openstack-mysql
    image: docker.iranserver.com/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'openstack-microsys-old'
      MYSQL_PASSWORD: '123456'
    volumes:
      - 'openstack-microsys-iranserver-com_openstack-mysql:/var/lib/mysql'
    networks:
      - my-services
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    restart: always

    ports:
      - 3310:3306

volumes:
  openstack-microsys-iranserver-com_openstack-mysql:
    external: true
  management_logs_volume:
    external: true
networks:
  my-services:
    external: true
