version: '3.8'

services:
  nodejs:
    build: 
      context: ./NodeJs
      dockerfile: DockerFile
    container_name: nodejs
    hostname: nodejs
    ports:
      - "8080:8080"
    volumes:
      - ./../view:/usr/src/app
    command: >
      sh -c "node -v && npm -v && npm start"

networks:
  my-services:
    external: true